name: Linux

on: [push, pull_request]

jobs:
  linux:
    name: ${{ matrix.platform.compiler }} ${{ matrix.mode }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - compiler: "Clang"
            os: "ubuntu-latest"
          - compiler: "GNU"
            os: "ubuntu-latest"
          - compiler: "ARMClang"
            os: "ubuntu-24.04-arm"
          - compiler: "ARMCC"
            os: "ubuntu-24.04-arm"
        mode: ["release"]
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_COMPILER_ID=${{ matrix.platform.compiler }} -DCMAKE_CXX_FLAGS="-Wall -Wconversion -Werror -Wextra -Wshadow -pedantic" -DENABLE_TESTS=ON .
      - name: Build
        run: cmake --build .
