name: Linux

on: [push, pull_request]

jobs:
  linux:
    name: ${{ matrix.compiler }} ${{ matrix.mode }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler: ["clang++", "g++"]
        os: ["ubuntu-latest", "ubuntu-24.04-arm"]
        mode: ["release"]
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: threeal/cmake-action@v2
        with:
          cxx-compiler: ${{ matrix.compiler }}
          cxx-flags: -Wall -Wconversion -Werror -Wextra -Wshadow -pedantic
          generator: Ninja
          options: |
            CMAKE_BUILD_TYPE=${{ matrix.mode }}
            ENABLE_TESTS=ON
